version: '3'

services:
  db-gestao-vagas:
    container_name: db_gestao_vagas
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db-gestao-vagas
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"