spring:
  datasource:
    url: jdbc:postgres://localhost:5432/gestao-vagas
    username: admin
    password: admin
#    url: ${DATABASE_URL}
#    username: ${DATABASE_USER}
#    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresSQLDialect

jwtCandidate:
  secret: "JAVAGAS_CANDIDATE_@321#"

jwtCompany:
  secret: "JAVAGAS_@321#"

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
